# -*- coding: utf-8 -*-
"""ShAI_BootCamp_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vVow4gNWZdGtMnyb9ZzRsaCtYASFc6uZ

#About Dataset
salaries dataset generally provides information about the employees of an organization in relation to their compensation. It typically includes details such as how much each employee is paid (their salary), their job titles, the departments they work in, and possibly additional information like their level of experience, education, and employment history within the organization.

# Features
- 'Id'
- 'EmployeeName'
- 'JobTitle'
- 'BasePay'
- 'OvertimePay'
- 'OtherPay'
- 'Benefits'
- 'TotalPay' -> salary
- 'TotalPayBenefits'
- 'Year'
- 'Notes'
- 'Agency'
- 'Status'

# Tasks

1. **Basic Data Exploration**: Identify the number of rows and columns in the dataset, determine the data types of each column, and check for missing values in each column.

2. **Descriptive Statistics**: Calculate basic statistics mean, median, mode, minimum, and maximum salary, determine the range of salaries, and find the standard deviation.

3. **Data Cleaning**: Handle missing data by suitable method with explain why you use it.

4. **Basic Data Visualization**: Create histograms or bar charts to visualize the distribution of salaries, and use pie charts to represent the proportion of employees in different departments.

5. **Grouped Analysis**: Group the data by one or more columns and calculate summary statistics for each group, and compare the average salaries across different groups.

6. **Simple Correlation Analysis**: Identify any correlation between salary and another numerical column, and plot a scatter plot to visualize the relationship.

8. **Summary of Insights**: Write a brief report summarizing the findings and insights from the analyses.

# Very Important Note
There is no fixed or singular solution for this assignment, so if anything is not clear, please do what you understand and provide an explanation.
"""

import pandas as pd
import numpy as np

# Load your dataset
df = pd.read_csv('/content/Salaries.csv')
df.head()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Task 1: Basic Data Exploration
df = pd.read_csv("Salaries.csv")

# Display number of rows and columns
num_rows, num_columns = df.shape
print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_columns}")

# Display data types of each column
print("\nData types of each column:")
print(df.dtypes)

# Check for missing values in each column
print("\nMissing values in each column:")
print(df.isnull().sum())

# Task 2: Descriptive Statistics
print("\nDescriptive Statistics:")
print(df[['BasePay', 'OvertimePay', 'OtherPay', 'Benefits', 'TotalPay', 'TotalPayBenefits']].describe())

# Task 3: Data Cleaning
# Handling missing data by dropping rows with missing values
df_cleaned = df.dropna()

# Task 4: Basic Data Visualization
# Create histograms to visualize the distribution of salaries
plt.figure(figsize=(10, 6))
plt.hist(df_cleaned['TotalPay'], bins=30, edgecolor='black', alpha=0.7)
plt.title('Distribution of Salaries')
plt.xlabel('Total Pay')
plt.ylabel('Frequency')
plt.show()

# Use pie chart to represent the proportion of employees in different departments
plt.figure(figsize=(10, 6))
df['JobTitle'].value_counts().head(10).plot.pie(autopct='%1.1f%%')
plt.title('Proportion of Employees in Top 10 Job Titles')
plt.show()

# Task 5: Grouped Analysis
grouped_df = df.groupby('Year')['TotalPay'].mean()
print("\nAverage Salaries by Year:")
print(grouped_df)

# Task 6: Simple Correlation Analysis
correlation = df[['TotalPay', 'BasePay', 'OvertimePay', 'OtherPay', 'Benefits']].corr()
print("\nCorrelation Matrix:")
print(correlation)

# Visualize the relationship between 'TotalPay' and 'BasePay'
plt.figure(figsize=(10, 6))
sns.scatterplot(x='BasePay', y='TotalPay', data=df)
plt.title('Scatter Plot: TotalPay vs BasePay')
plt.xlabel('Base Pay')
plt.ylabel('Total Pay')
plt.show()

"""# Good Luck!"""